---
title: "City case studies"
output: 
  html_document: 
    df_print: paged
    fig_width: 5
    fig_height: 3.5
---

<hr>
#### Case studies have no distinct trend with city population size, although a few top global cities dominate the analysis
<br>

```{r include=FALSE}

rm(list = ls())
library(tidyverse)
library(svglite)

load(file = "Data/city_studies.RData")
load(file = "Data/city_data.RData")

ctop <- ctab %>%
  group_by(geo_city,geo_country,geo_pop) %>%
  summarise(n=n()) %>%
  arrange(desc(n)) %>%
  mutate(geo_pop=as.numeric(geo_pop))

ctop <- left_join(ctop,data_UN, by = c("geo_city" = "City")) %>%
  select(-c(Year,Country,Record.Type,Reliability,Value.Footnotes)) %>%
  group_by(geo_city) %>%
  filter(UN_pop==max(UN_pop) | is.na(UN_pop)==TRUE)

## use agglomeration data if we have it
ctop <- ctop %>%
  mutate(geo_pop=ifelse(UN_type=="Urban agglomeration" & is.na(UN_type)==FALSE,UN_pop,geo_pop))

ctop$population_category <- cut(ctop$geo_pop,breaks = c(100e6,10e6,1e6,3e5,0),dig.lab=10,include.lowest=TRUE)

blarg <- ctop %>%
  group_by(population_category,n==369,n==194,n==161,n==128,n==101,n==70,n==69,n==68,n==60,n==58,geo_pop==8307904,geo_city=="Paris") %>%
  summarise(no_cities=n(),mean_pop=mean(geo_pop),sum_articles=sum(n),mean_articles=mean(n),city_names=paste(geo_city, collapse=", ")) %>% 
  ungroup() %>% arrange(desc(population_category))

blarg<- blarg %>%
  mutate(city_names=ifelse(nchar(blarg$city_names)>15,"Other",city_names))

ctop <- ctop %>%
  group_by(population_category) %>%
  summarise(no_cities=n(),mean_pop=mean(geo_pop),sum_articles=sum(n),mean_articles=mean(n),city_names=paste(geo_city, collapse=", ")) %>%
  ungroup() %>% arrange(desc(population_category))


```

```{r  studies_v_population, echo=FALSE, warning=FALSE, rows.print=4, fig.path='Plots/', dev=c('png','pdf')}

blarg %>%
  ggplot(.,aes(x=reorder(population_category,mean_pop),y=sum_articles,fill=city_names)) +
  geom_bar(stat="identity") +
  scale_x_discrete(labels = c("<0.3m","0.3-1m","1-10m",">10m")) +
  xlab("Cities, grouped by population") +
  ylab("Total articles")

library(knitr)
library(kableExtra)
kable(ctop, "html", caption="Urban studies versus population",digits=1) %>%
  kable_styling() %>%
  scroll_box(height = "400px")

```

```{r post_AR5,echo=FALSE,warning=FALSE, rows.print=4, fig.path='Plots/', dev=c('png','pdf')}

### Post-AR5 literature expansion

AR5 <- ctab
AR5$AR5_category <- cut(AR5$year,breaks = c(1990,1995,2001,2007,2013,2018),include.lowest = TRUE)


AR5 <- AR5 %>% 
  filter(!is.na(UN6)) %>% 
  filter(!is.na(AR5_category)) %>% 
  group_by(AR5_category,UN6) %>% 
  summarise(n=n()) %>% 
  group_by(AR5_category) %>% 
  mutate(total=sum(n)) %>% 
  group_by(AR5_category,UN6) %>% 
  mutate(percent=n/total) %>% 
  select(-total)

p1 <- AR5 %>%
  ggplot(.,aes(x=AR5_category,y=n,fill=UN6)) +
  geom_bar(stat='identity') +
  guides(fill=FALSE)
  

p2 <- AR5 %>% 
  ggplot(.,aes(x=AR5_category,y=percent,fill=UN6))+
  geom_bar(stat='identity') +
  theme(legend.position="bottom")

library(gridExtra)
grid.arrange(p1,p2,nrow=1)

```

#### Case studies regionally mis-match the population breakdown of cities

```{r include=FALSE}


rm(list = ls())
library(tidyverse)
library(svglite)
library(xlsx)

load(file = "Data/city_studies.RData")
load(file="Data/geo_data.RData")
load(file = "Data/city_data.RData")

region='UN6'

## use agglomeration data if we have it
ctab <- left_join(ctab,data_UN, by = c("geo_city" = "City")) %>%
  select(-c(Year,Country,Record.Type,Reliability,Value.Footnotes))

ctab <- ctab %>%
  mutate(geo_pop=ifelse(UN_type=="Urban agglomeration" & is.na(UN_type)==FALSE,UN_pop,geo_pop))


######### merge studies into regional breakdown of cities and populations ######### 

ctab$population_category <- cut(ctab$geo_pop,breaks=c(100e6,10e6,1e6,3e5,1),dig.lab=10,include.lowest=TRUE,ordered_result = TRUE)


######## delete citations after 2016, due to time bias... ######## 
ctab$citations[ctab$year>2016] = NA;


ctab <- ctab %>%
  group_by_(region,'population_category') %>%
  summarise(no_studies=n(),study_cities=length(unique(geo_city)),citations=sum(citations,na.rm=TRUE)) %>%
  complete(population_category) %>% 
  ungroup()

ctab <- ctab %>%
  rbind(
    ctab %>% 
      group_by(population_category) %>%
      summarise(UN6="WORLD",no_studies=sum(no_studies,na.rm=TRUE),study_cities=sum(study_cities,na.rm=TRUE),
                citations=sum(citations,na.rm=TRUE)) %>%
      ungroup() %>%
      select(UN6,population_category,no_studies,study_cities,citations)
  ) %>%
  filter(!is.na(UN6))

####################### 

data_proj$area <- gsub("LATIN AMERICA AND THE CARIBBEAN","LATIN AMERICA",data_proj$area)
data_proj$area <- gsub("NORTHERN AMERICA","NORTH AMERICA",data_proj$area)

data_proj <- data_proj %>%
  filter(area=="WORLD" | area=="AFRICA" | area=="ASIA" | area=="EUROPE" | area=="LATIN AMERICA" | area=="NORTH AMERICA" | area=="OCEANIA")

data_proj <- data_proj %>% 
  filter(size_code %in% c(1,6)) %>% 
  mutate(size=ifelse(size_code==1,"(10000000,100000000]",size)) %>%
  mutate(size=ifelse(size_code==6,"[1,300000]",size)) %>%
  rbind(
    data_proj %>%
      filter(size_code %in% c(2,3)) %>% 
      group_by(area,year,type) %>%
      summarise(value=sum(value)) %>% 
      ungroup() %>% 
      mutate(size_code=23,size="(1000000,10000000]") %>% 
      select(area,size,size_code,type,year,value)
  ) %>% 
  rbind(
    data_proj %>%
      filter(size_code %in% c(4,5)) %>% 
      group_by(area,year,type) %>%
      summarise(value=sum(value)) %>% 
      ungroup() %>% 
      mutate(size_code=45,size="(300000,1000000]") %>% 
      select(area,size,size_code,type,year,value)
  ) %>%
  filter(type!="Percentage of urban population") %>% 
  select(-size_code)
  
data_proj <- data_proj %>%
  mutate(value=ifelse(type=="Population",value*1000,value)) %>%
  filter(year %in% c(2015,2030)) %>%
  unite(var,type:year) %>% 
  spread(var,value)

### join

blarg <- left_join(ctab,data_proj,by=c("UN6"="area","population_category"="size"))



#### calculate ratios, global first

all_studies <- sum(blarg$no_studies[data_proj$area=="WORLD"])
world_pop_2015 <- sum(data_proj$Population_2015[data_proj$area=="WORLD"])
world_pop_2030 <- sum(data_proj$Population_2030[data_proj$area=="WORLD"])

blarg <- blarg %>%
  mutate(average_citations=citations/no_studies) %>%
  mutate(ratio_studies_global=no_studies/all_studies) %>%
  mutate(ratio_pop_2015_global=Population_2015/world_pop_2015) %>%
  mutate(ratio_pop_2030_global=Population_2030/world_pop_2030)

#### regional

blarg <- blarg %>% 
  group_by(UN6) %>% 
  mutate(region_pop_2015=sum(Population_2015,na.rm=TRUE)) %>% 
  mutate(region_pop_2030=sum(Population_2030,na.rm=TRUE)) %>% 
  mutate(region_studies=sum(no_studies,na.rm=TRUE)) %>%
  ungroup() %>% 
  mutate(ratio_studies_region=no_studies/region_studies) %>% 
  mutate(ratio_pop_2015_region=Population_2015/region_pop_2015) %>% 
  mutate(ratio_pop_2030_region=Population_2030/region_pop_2030) %>%
  select(-region_pop_2015,-region_pop_2030,-region_studies)


blarg$population_category <- as.factor(blarg$population_category)
blarg$population_category <- factor(blarg$population_category,levels(blarg$population_category)[c(4,3,1,2)])


```


```{r study_distribution, echo=FALSE,warning=FALSE, fig.width=12, fig.height=5,fig.path="Plots/",dev=c('png','pdf')}

####################### fraction of case studies and population (relative to region) #######################

blarg %>%
  ggplot(.) +
  geom_point(aes(x=UN6,y=ratio_studies_region),stat='identity',colour='blue') +
  geom_point(aes(x=UN6,y=ratio_pop_2015_region),stat='identity',colour='black') +
  geom_point(aes(x=UN6,y=ratio_pop_2030_region),stat='identity',colour='red') +
  geom_segment(aes(x=UN6,yend=ratio_studies_region+ifelse(ratio_studies_region>ratio_pop_2015_region,-0.015,0.015),xend=UN6,
                   y=ratio_pop_2015_region+ifelse(ratio_studies_region>ratio_pop_2015_region,0.015,-0.015)),arrow=arrow(length=unit(0.3,"cm"))) + 
  facet_grid(. ~ population_category) +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
  ggtitle("proportion of studies relative to urban inhabitats in each city size, by region (arrow going up = overrepresented)")



####################### average citations by region / city size #######################

blarg %>%
  ggplot(.,aes(x=population_category,y=average_citations,fill=UN6)) + 
  guides(fill=FALSE) +
  geom_bar(stat='identity') +
  facet_grid(reformulate(region)) +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))

####################### Case studies vs. population shares & projections #######################

blarg %>%
  mutate(ratio=ratio_studies_global/ratio_pop_2030_global) %>%
  mutate(ratio=ifelse(ratio_studies_global<ratio_pop_2030_global,2-(ratio_pop_2030_global/ratio_studies_global),ratio)) %>% 
  ggplot(.) +
  geom_point(aes(x=population_category,y=ratio),stat='identity',colour='blue') +
  facet_grid(.~ UN6)+
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))

# summary <- blarg %>% 
#   group_by(UN6) %>% 
#   summarise(total_cities=sum(geo_cities,na.rm=TRUE),total_study_cities=sum(study_cities,na.rm=TRUE),total_studies=sum(no_studies,na.rm=TRUE))

####################### coverage of cities ####################### 

blarg %>% 
  ggplot(.,aes(x=population_category,y=study_cities/`Number of agglomerations_2015`,fill=UN6)) + 
  guides(fill=FALSE) +
  geom_bar(stat='identity') +
  facet_grid(reformulate(region)) +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))

blarg %>% 
  filter(!population_category=='[1,300000]') %>% 
  ggplot(.,aes(x=UN6,y=study_cities/`Number of agglomerations_2015`,fill=population_category)) + 
  guides(fill=FALSE) +
  geom_bar(stat='identity') +
  facet_grid(.~population_category)




blarg$population_category <- as.factor(blarg$population_category)
blarg$population_category <- factor(blarg$population_category,levels(blarg$population_category)[c(4,3,1,2)])

data_proj$size <- as.factor(data_proj$size)
data_proj$size <- factor(data_proj$size,levels(data_proj$size)[c(4,3,1,2)])


data_proj %>%
  #gather(key,value,Population_2015:Population_2030) %>%
  mutate(growth_rate=(Population_2030/Population_2015)^(1/15)-1) %>% 
  ggplot(.) + 
  #geom_bar(aes(x=key,y=value),stat='identity') + 
  geom_bar(aes(x=size,y=growth_rate,fill=area),stat='identity') +
  facet_grid(.~area) +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))

data_proj %>% 
  filter(area=="WORLD") %>% 
  group_by(area) %>% 
  mutate(total_2015=sum(Population_2015),total_2030=sum(Population_2030)) %>% 
  ungroup() %>% 
  mutate(Population_2015=Population_2015/total_2015,Population_2030=Population_2030/total_2030) %>% 
  gather(key,value,Population_2015:Population_2030) %>% 
  ggplot(.) +
  geom_bar(aes(x=key,y=value,fill=size),stat='identity',position=position_stack(reverse = TRUE))

data_proj %>% 
  filter(area!="WORLD") %>% 
  ggplot(.) +
  geom_bar(aes(x=size,y=Population_2030,fill=area),stat='identity') +
  facet_grid(.~area) +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))

zz<- blarg %>%
  group_by(UN6) %>% 
  summarise(total_studies = sum(no_studies,na.rm=TRUE),total_pop=sum(Population_2015,na.rm=TRUE)) %>% 
  mutate(fraction_studies=total_studies/5570,fraction_pop=total_pop/3957285013) %>% 
  gather(key,value,fraction_studies:fraction_pop) %>% 
  filter(!UN6 =="WORLD")
zz %>% 
  ggplot(.)+
  geom_bar(aes(x=UN6,y=value,fill=key),stat='identity',width=.5, position = "dodge")

```

<hr>
### The structure of comparative research 
<br>

```{r include=FALSE}

rm(list = ls())
library(tidyverse)
library(svglite)

load(file = "Data/city_studies.RData")
load(file = "Data/city_data.RData")


## use agglomeration data if we have it
ctab <- left_join(ctab,data_UN, by = c("geo_city" = "City")) %>%
  select(-c(Year,Country,Record.Type,Reliability,Value.Footnotes))

ctab <- ctab %>%
  mutate(geo_pop=ifelse(UN_type=="Urban agglomeration" & is.na(UN_type)==FALSE,UN_pop,geo_pop))

ctab <- ctab %>%
  group_by(title) %>%
  mutate(comparative = ifelse(n()>1,1,0)) %>%
  select(geo_city:year,comparative,everything())

ctab$population_category <- cut(ctab$geo_pop,breaks = c(100e6,10e6,1e6,3e5,0),dig.lab=10,include.lowest=TRUE)

blarg <- ctab %>%
  filter(comparative==1)

names <- sort(unique(blarg$UN6))
names_cities <- sort(unique(blarg$geo_city))
comp <- matrix(data=0,nrow=length(names),ncol=length(names),dimnames=list(names,names))

blarg <- blarg %>% 
  filter(is.na(UN6)==FALSE) %>% 
  group_by(title,abstract,doi) %>% 
  summarise(regions=paste(UN6,collapse=";"),cities=paste(geo_city,collapse=";"),n=n()) %>%
  arrange(desc(n)) %>%
  filter(n!=1)
  
for (i in 1:length(blarg$title)) {

  temp_regs <- strsplit(blarg$regions[i],';')


  if (length(temp_regs[[1]])>1) {

    combos <- combn(temp_regs[[1]],2)

    for (j in 1:length(combos[1,])) {

      comp[combos[1,j],combos[2,j]] <- comp[combos[1,j],combos[2,j]] + 1
      comp[combos[2,j],combos[1,j]] <- comp[combos[2,j],combos[1,j]] + 1

    }
  }
}

ratio_comp <- comp

for (i in 1:length(ratio_comp[1,])) {

  ratio_comp[i,] <- ratio_comp[i,]/sum(ratio_comp[i,])

}


asd <- blarg %>% 
  mutate(intl=ifelse(length(unique(strsplit(regions,';')[[1]]))==1,0,1)) %>% 
  filter(intl==1,n>2)


```

```{r comparative_Studies, echo=FALSE,warning=FALSE, rows.print=4, fig.path="Plots/",dev=c('png','pdf')}
library(circlize)
chordDiagram(comp)

blarg %>%
  rename(city_count=n) %>%
  group_by(city_count) %>%
  summarise(study_count=n()) %>%
  ggplot(.,aes(x=city_count,y=study_count)) +
  geom_bar(stat='identity')

```

# Topics by city and region


```{r include=FALSE}

rm(list = ls())
library(tidyverse)
library(svglite)

load(file = "Data/city_studies.RData")

######### adjusted for global distribution ######### 



blarg <- gather(ctab,topic,value,"Cooling_demand":"Water_demand") %>% 
  filter(topic!="China_urban_development")

global_topic_score = sum(blarg$value)

regions <- blarg %>%
  group_by(UN6) %>%
  filter(!is.na(UN6)) %>%
  mutate(total_score=sum(value)) %>%
  ungroup() %>%
  group_by(UN6,topic) %>%
  summarise(value=sum(value)/first(total_score))

cities <- blarg %>%
  group_by(geo_city) %>%
  mutate(topic_score=sum(value)) %>%
  group_by(geo_city,topic) %>%
  summarise(value=sum(value)/first(topic_score),n=n()) %>%
  arrange(desc(n))

cities_topic_count <- blarg %>% 
  mutate(value=ifelse(value>0.02,1,0)) %>% 
  spread(topic,value) %>% 
  group_by(geo_city) %>%
  mutate(total_docs=n()) %>%
  ungroup() %>%
  gather(topic,value,"Buildings":"Water_demand") %>% 
  group_by(geo_city,topic) %>% 
  summarise(value=sum(value),total_docs=first(total_docs)) %>% 
  spread(topic,value) %>% 
  arrange(desc(total_docs))

z <- cities %>%
  group_by(geo_city) %>%
  summarise(n=first(n)) %>%
  arrange(desc(n))

cities$city_ordered <- factor(cities$geo_city,levels=z$geo_city)

```

```{r topic_distribution,echo=FALSE,warning=FALSE, fig.width=8,fig.height=6,fig.path="Plots/",dev=c('png','pdf')}


####################### no of studies per region and pop category #######################

regions %>%
  ggplot(.,aes(UN6,topic)) +
  geom_tile(aes(fill=value),colour="grey50") +
  scale_fill_distiller(palette = "YlGnBu",direction=1,na.value = "white") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
  ggtitle("Summed topics, normalised by region")

topic_summary_summed <- regions %>%
  group_by(UN6) %>%
  arrange(desc(value)) %>%
  summarise(top_topics = paste0(c(nth(topic,1),nth(topic,2),nth(topic,3)),collapse="; "),low_topics = paste0(c(nth(topic,16),nth(topic,15),nth(topic,14)),collapse="; "))

city_summary_summed <- cities %>%
  filter(n>40) %>%
  group_by(geo_city) %>%
  arrange(desc(value)) %>%
  summarise(n=first(n),top_topics=paste0(c(nth(topic,1),nth(topic,2),nth(topic,3)),collapse="; "),low_topics = paste0(c(nth(topic,16),nth(topic,15),nth(topic,14)),collapse="; ")) %>%
  arrange(desc(n))

africa_cities <- ctab %>%
  filter(geo_city=="Cairo") %>%
  gather(key="topic",value="value","Cooling_demand":"Water_demand") %>% 
  group_by(title,abstract) %>% 
  filter(value>0.025) %>% 
  mutate(topics=paste0(topic,collapse="; ")) %>% 
  summarise(geo_city=first(geo_city),year=first(year),topics=first(topics),authors=first(authors),doi=first(doi)) %>%
  arrange(desc(year)) %>% 
  select(title,year,authors,topics,doi)
  

cities_topic_count$ordered <- factor(cities_topic_count$geo_city,levels=z$geo_city)

cities_topic_count %>% 
  gather(topic,value,"Buildings":"Water_demand") %>% 
  filter(total_docs>57) %>% 
  mutate(value=ifelse(value==0,NA,value)) %>% 
  ggplot(.,aes(ordered,topic)) +
  geom_tile(aes(fill=value/total_docs),colour="grey50") +
  geom_text(aes(label = round(value, 1))) +
  scale_fill_distiller(palette = "YlGnBu",direction=1,na.value = "grey") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) + 
  guides(fill=FALSE) 

# random sample #

zz <- ungroup(cities_topic_count) %>% 
  filter(total_docs>30) %>% 
  sample_n(10)

zz %>% 
  gather(topic,value,"Buildings":"Water_demand") %>% 
  mutate(value=ifelse(value==0,NA,value)) %>% 
  ggplot(.,aes(ordered,topic)) +
  geom_tile(aes(fill=value/total_docs),colour="grey50") +
  geom_text(aes(label = round(value, 1))) +
  scale_fill_distiller(palette = "YlGnBu",direction=1,na.value = "grey") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) + 
  guides(fill=FALSE) 


library(xlsx)

topic_summary_summed <- t(topic_summary_summed)
city_summary_summed <- t(city_summary_summed)
africa_cities <- t(africa_cities)

library(knitr)
library(kableExtra)

kable(cities_topic_count, "html", caption="No. studies by city and topic",digits=1) %>% 
  kable_styling()

kable(topic_summary_summed, "html", caption="Summed top and bottom topics for regions",digits=1) %>%
  kable_styling()

kable(city_summary_summed, "html", caption="Summed top and bottom topics for cities",digits=1) %>%
  kable_styling()

kable(africa_cities, "html", caption="papers on Cairo",digits=1) %>%
  kable_styling()

write.xlsx(as.data.frame(africa_cities),file='Writing/cairo.xlsx')

```


```{r map,echo=FALSE,warning=FALSE,fig.width=10,fig.height=8,fig.path="Plots/",dev=c('png','pdf')}

#################### Maps ####################


rm(list = ls())
library(tidyverse)
library(ggmap)
library(maps)
library(mapdata)
library(xlsx)

load(file = "Data/city_studies.RData")

####################  get world map together ####################  

regions <- read.xlsx(file="C:\\Users\\lamw\\Documents\\SpiderOak Hive\\Work\\Code\\MATLAB\\Data shop\\Region definitions\\regions.xls",sheetName = "Sheet1") %>%
  select(ISO.Code,IAM10,UN6)
regions$UN6 <- gsub("LATIN AMERICA AND THE CARIBBEAN","LATIN AMERICA",regions$UN6)
regions$UN6 <- gsub("NORTHERN AMERICA","NORTH AMERICA",regions$UN6)

isos <- read.xlsx(file="C:\\Users\\lamw\\Documents\\SpiderOak Hive\\Work\\Code\\MATLAB\\Handy code\\ISOcodes.xls",sheetName="3 letter codes",startRow = 3,colIndex=7:8,header=FALSE)
names(isos) = c("country","iso")
isos <- isos %>% mutate(country=tolower(country))

world <- map_data("world") %>%
  filter(region != "Antarctica") %>%
  mutate(region=tolower(region))

world <- left_join(world,isos,by=c("region"="country"))
world <- left_join(world,regions,by=c("iso"="ISO.Code"))


####################  get city location data ####################  

blarg <- ctab %>%
  group_by(geo_city) %>%
  summarise(location=first(location),n=n(),UN6=first(UN6)) %>%
  mutate(location=str_extract(location,"\\([^()]+\\)")) %>%
  mutate(lat=as.numeric(str_extract(location,"([^(][0-9[[:punct:]]]+)[[:blank:]]"))) %>%
  mutate(long=as.numeric(str_extract(location,"([[:blank:]][0-9[[:punct:]]][^)]+)"))) %>%
  select(-location)


####################  plot ####################  


ggplot() + 
  geom_polygon(data = world, aes(x=long, y = lat, group = group, fill=UN6),color="white") + 
  theme_void() +
  coord_fixed(1) +
  geom_point(data=blarg,aes(x=lat,y=long,size=n,fill=UN6),color="black",fill="#636363",shape=21)








```

```{r include=FALSE}

############## deep diving ############## 

rm(list = ls())
library(tidyverse)
load(file = "Data/city_studies.RData")

### Africa buildings

AF <- ctab %>%
  filter(UN6=="AFRICA") %>%
  arrange(desc(Households))


EU <- ctab %>%
  filter(UN6=="EUROPE") %>%
  arrange(desc(Households))


```


```{r include=FALSE}

############## future looking cases ############## 


rm(list = ls())
library(tidyverse)
load(file = "Data/city_studies.RData")

ctab <- ctab %>%
  mutate(tags=ifelse(grepl("future",tags),1,0))

futures_by_region <- ctab %>%
  group_by(UN6) %>%
  summarise(n=n(),futures=sum(tags)) %>%
  mutate(proportion=futures/n)

futures_by_topic <- ctab %>%
  gather(topic,value,'Cooling_demand':'Water_demand') %>% 
  filter(tags==1)

topic_sum <- sum(futures_by_topic$value)

futures_by_topic <- futures_by_topic %>% 
  group_by(topic) %>% 
  summarise(total_value=topic_sum,value=sum(value)) %>% 
  mutate(proportion=value/total_value) %>% 
  arrange(desc(proportion))
  



blarg <- ctab %>%
  mutate(tags=ifelse(grepl("future",tags),1,0)) %>%
  filter(UN6=='AFRICA' & tags==1)

```


# Typology linking


``` {r include=FALSE}

############## typology ############## 

rm(list = ls())
library(tidyverse)
library(xlsx)
load(file = "Data/city_studies.RData")
load(file = "Data/geo_data.RData")

city_list <- read.xlsx(file = "Data/city typology.xlsx",sheetName = "Sheet1",header=FALSE,encoding="UTF-8")

typology <- data.frame(City=as.character(),cluster=integer())

for (i in 1:length(city_list[,1])) {
  temp <- strsplit(as.character(city_list[i,2]),split=",")
  for (j in 1:length(temp[[1]])) {
    
    typology <- add_row(typology,City=temp[[1]][j],cluster=city_list[i,1])
    
  }
}

typology$City <- textclean::replace_non_ascii(typology$City)


### normalise city names

data_geo <- data_geo %>% 
  filter(featurecode!="PPLX") %>% 
  mutate(alternatenames=as.character(alternatenames))


####### add new manual exceptions

data_geo$alternatenames[grep("Urumqi",data_geo$alternatenames)] <- paste0("Wulumqi,",data_geo$alternatenames[grep("Urumqi",data_geo$alternatenames)])

data_geo$alternatenames[grep("Harbin",data_geo$alternatenames)] <- paste0("Haerbin,",data_geo$alternatenames[grep("Harbin",data_geo$alternatenames)])

data_geo$alternatenames[grep("Hong Kong",data_geo$alternatenames)] <- paste0("HongKong,",data_geo$alternatenames[grep("Hong Kong",data_geo$alternatenames)])

data_geo$alternatenames[grep("Rio de Janeiro",data_geo$alternatenames)] <- paste0("Rio de Janiero,",data_geo$alternatenames[grep("Rio de Janeiro",data_geo$alternatenames)])

data_geo$alternatenames[grep("Stockholm",data_geo$city)] <- paste0("Stockholm county,",data_geo$alternatenames[grep("Stockholm",data_geo$city)])

data_geo$alternatenames[grep("Gävle",data_geo$city)] <- paste0("Gavle,",data_geo$alternatenames[grep("Gävle",data_geo$city)])

data_geo$alternatenames[grep("Buffalo City",data_geo$alternatenames)] <- ""

data_geo$alternatenames[grep(5110629,data_geo$geonameid)] <- paste0("Buffalo City,",data_geo$alternatenames[grep(5110629,data_geo$geonameid)])


data_geo$alternatenames[grep(3882428,data_geo$geonameid)] <- ""

#######

typology <- typology %>% 
  mutate(City=as.character(City)) %>% 
  rowwise() %>% 
  mutate(standardname=ifelse(any(grepl(City,data_geo$alternatenames))==FALSE,NA,as.character(data_geo$city[grep(paste0("(,|^)\\<",City,"\\>(,|$)"),data_geo$alternatenames)]))) 


typology <- typology %>% 
  rowwise() %>% 
  mutate(City=ifelse(is.na(standardname)==FALSE,standardname,City))


###
blarg <- left_join(ctab,typology,by=c("geo_city"="City")) %>% 
  filter(!is.na(cluster)) %>% 
  group_by(cluster) %>% 
  mutate(total_studies=n(),unique_cities=length(unique(geo_city)),cities=paste0(unique(geo_city),collapse="; "))

blarg <- gather(blarg,topic,value,"Cooling_demand":"Water_demand") 

### match failed cases
typology <- typology %>% 
  mutate(standardname=ifelse(is.na(standardname)==TRUE,"No known city","No documents"))
fails <- anti_join(typology,ctab,by=c("City"="geo_city"))

```

``` {r typology_topics,echo=FALSE,warning=FALSE,fig.width=8,fig.height=6,fig.path="Plots/",dev=c('png','pdf')}

typology_topic_count <- blarg %>% 
  mutate(value=ifelse(value>0.02,1,0)) %>% 
  spread(topic,value) %>% 
  group_by(cluster) %>%
  mutate(total_docs=n()) %>%
  ungroup() %>%
  gather(topic,value,"Buildings":"Water_demand") %>% 
  group_by(cluster,topic) %>% 
  summarise(value=sum(value),total_docs=first(total_docs)) %>% 
  spread(topic,value) %>% 
  arrange(desc(total_docs)) %>% 
  select(-China_urban_development)


typology_topic_count %>% 
  gather(topic,value,"Buildings":"Water_demand") %>% 
  mutate(value=ifelse(value==0,NA,value)) %>% 
  ggplot(.,aes(cluster,topic)) +
  geom_tile(aes(fill=value/total_docs),colour="grey50") +
  geom_text(aes(label = round(value, 1))) +
  scale_fill_distiller(palette = "YlGnBu",direction=1,na.value = "grey") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) + 
  guides(fill=FALSE) 


blarg %>% 
  group_by(cluster) %>% 
  mutate(total_score=sum(value)) %>% 
  ungroup() %>% 
  group_by(cluster,topic) %>% 
  summarise(value=sum(value)/first(total_score)) %>% 
  ggplot(.,aes(cluster,topic)) +
  geom_tile(aes(fill=value),colour="grey50") +
  scale_fill_distiller(palette = "YlGnBu",direction=1,na.value = "white") +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
  ggtitle("Summed topics, normalised by cluster") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 8))

# global_topic_score = sum(blarg$value)
# 
# blarg %>% 
#   group_by(topic) %>% 
#   mutate(global_topic_dist=sum(value)/global_topic_score) %>% 
#   group_by(cluster) %>% 
#   mutate(total_score=sum(value)) %>% 
#   ungroup() %>% 
#   group_by(cluster,topic) %>% 
#   summarise(value=log((sum(value)/first(total_score))/first(global_topic_dist)))%>% 
#   ggplot(.,aes(cluster,topic)) +
#   geom_tile(aes(fill=value),colour="grey50") +
#   scale_fill_distiller(palette = "YlGnBu",direction=1,na.value = "white") +
#   theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
#   ggtitle("Summed topics, normalised by global topic distribution") +
#   scale_x_continuous(breaks = scales::pretty_breaks(n = 8))


summary <- blarg %>% 
  group_by(cluster,topic) %>% 
  summarise(value=sum(value),total_studies=first(total_studies),unique_cities=first(unique_cities),cities=first(cities)) %>% 
  group_by(cluster) %>% 
  arrange(desc(value)) %>% 
  summarise(no_studies=first(total_studies),unique_cities=first(unique_cities),cities=first(cities),top_topics = paste0(c(nth(topic,1),nth(topic,2),nth(topic,3)),collapse="; "),low_topics = paste0(c(nth(topic,17),nth(topic,16),nth(topic,15)),collapse="; "))


library(knitr)
library(kableExtra)
kable(summary, "html", caption="Typology clusters, documents and topics",digits=1) %>%
  kable_styling() %>%
  scroll_box(height = "500px")


kable(fails,"html", caption="Typology cities without matches",digits=1) %>%
  kable_styling() %>%
  scroll_box(height = "200px")

write.xlsx(as.data.frame(summary),file='Writing/typology.xlsx')


```

``` {r include=FALSE}


# rm(list = ls())
# library(tidyverse)
# library(xlsx)
# load(file = "Data/city_studies.RData")
# load(file = "Data/geo_data.RData")
# 
# 
# ctop <- ctab %>% 
#   group_by(geo_city) %>% 
#   summarise(n=n()) %>% 
#   arrange(desc(n))
# 
# blarg <- ctab %>% 
#  # filter(grepl(paste0(ctop$geo_city,collapse="|"),geo_city)) %>% 
#   gather(topic,value,'Air pollution':'Water demand') %>% 
#   mutate(value=ifelse(value>0.025,1,0)) %>% 
#   spread(topic,value)
# 
# 
# zz <- blarg %>% 
#   filter(geo_city=="Berlin")
# 
# 
# ctab %>% 
#   ggplot(.,aes(`Climate policies & governance`))+
#   geom_histogram()
#   
# ctab %>% 
#   gather(topic,value,'Air pollution':'Water demand') %>% 
#   ggplot(.,aes(value)) +
#   geom_histogram(binwidth=0.01) +
#   scale_x_continuous(limits = c(-0.1,0.2))
# 
# 
# ggplot(.,aes(ordered,topic)) +
#   geom_tile(aes(fill=value/total_docs),colour="grey50") +
#   geom_text(aes(label = round(value, 1))) +
#   scale_fill_distiller(palette = "YlGnBu",direction=1,na.value = "grey") +
#   theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))

``` 

```{r include=FALSE}

### look at google scholar cases

# 
# rm(list = ls())
# library(tidyverse)
# library(svglite)
# library(xlsx)
# 
# ctab <-
#   read.csv("Data/cities_googlescholar.csv",sep=",",header=TRUE, encoding="UTF-8") %>%
#   subset(select=-c(X)) %>%
#   select(cities,countries,year,title,abstract,doi,authors,everything()) %>%
#   rename(geo_city=cities,geo_country=countries,geo_pop=population)
# 
# 
# for (i in 1:length(ctab[,1])) {
#   temp_cities <- as.character(ctab$geo_city[i])
#   temp_countries <- as.character(ctab$geo_country[i])
#   temp_pop <- as.character(ctab$geo_pop[i])
#   if(grepl(';',temp_cities)=="TRUE") {
#     temp_cities <- strsplit(temp_cities,';')
#     temp_countries <- strsplit(temp_countries,';')
#     temp_pop <- strsplit(temp_pop,';')
#     for (j in 1:length(temp_cities[[1]])) {
#       rowtobind <- ctab[i,]
#       rowtobind$geo_city <- temp_cities[[1]][j]
#       rowtobind$geo_country <- temp_countries[[1]][j]
#       rowtobind$geo_pop <- temp_pop[[1]][j]
#       ctab <- rbind(ctab,rowtobind)
#     }
#   }
# }
# 
# ctab <- ctab[!(grepl(';',ctab$geo_city)),] %>%
#   mutate(geo_city=trimws(geo_city))
# ctab <- ctab[!(grepl(';',ctab$geo_country)),] %>%
#   mutate(geo_country=trimws(geo_country))
# ctab <- ctab[!(grepl(';',ctab$geo_pop)),] %>%
#   mutate(geo_pop=trimws(geo_pop))
# 
# 
# regions <- read.xlsx(file="C:\\Users\\lamw\\Google Drive\\Work\\Code\\MATLAB\\Data shop\\Region definitions\\regions.xls",sheetName = "Sheet1") %>%
#   select(ISO.Code,IAM10,UN6)
# regions$UN6 <- gsub("LATIN AMERICA AND THE CARIBBEAN","LATIN AMERICA",regions$UN6)
# regions$UN6 <- gsub("NORTHERN AMERICA","NORTH AMERICA",regions$UN6)
# 
# ctab <- ctab %>%
#   left_join(regions,by=c("geo_country"="ISO.Code")) %>%
#   select(geo_city,geo_country,IAM10,UN6,geo_pop,citations,everything()) %>%
#   mutate(geo_pop=as.numeric(geo_pop))
# 
# blarg <- ctab %>% 
#   group_by(UN6) %>% 
#   summarise(n=n(),percent=n()/4311*100)



``` 
